-- =============================================================================
-- Async-mail tenant_id refactor
--
-- Converts the previously element-collection tables (ASYNC_MAIL_TO,
-- ASYNC_MAIL_BCC, ASYNC_MAIL_CC, ASYNC_MAIL_HEADER) into first-class domain
-- tables so each row can carry TENANT_ID, consistent with ASYNC_MAIL_MESS.
-- Also adds TENANT_ID to ASYNC_MAIL_ATTACHMENT.
--
-- DBMS: Oracle. Adapt PRIMARY KEY drop syntax for other vendors.
-- Run inside a single transaction; verify each step before committing.
-- =============================================================================

-- ---------- Sequences for the new synthetic IDs --------------------------------
CREATE SEQUENCE ASYNC_MAIL_TO_ID_SEQ         START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE ASYNC_MAIL_BCC_ID_SEQ        START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE ASYNC_MAIL_CC_ID_SEQ         START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE ASYNC_MAIL_HEADER_ID_SEQ     START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

-- ---------- ASYNC_MAIL_TO ------------------------------------------------------
ALTER TABLE ASYNC_MAIL_TO ADD (ID NUMBER(19), TENANT_ID NUMBER(19));
UPDATE ASYNC_MAIL_TO SET ID = ASYNC_MAIL_TO_ID_SEQ.NEXTVAL;
UPDATE ASYNC_MAIL_TO t
   SET TENANT_ID = (SELECT TENANT_ID FROM ASYNC_MAIL_MESS m WHERE m.ID = t.MESSAGE_ID);


ALTER TABLE ASYNC_MAIL_TO MODIFY (ID NOT NULL, TENANT_ID NOT NULL);
ALTER TABLE ASYNC_MAIL_TO ADD CONSTRAINT PK_ASYNC_MAIL_TO PRIMARY KEY (ID);

CREATE INDEX IDX_ASYNC_MAIL_TO_TENANT ON ASYNC_MAIL_TO(TENANT_ID);
CREATE INDEX IDX_ASYNC_MAIL_TO_MSG    ON ASYNC_MAIL_TO(MESSAGE_ID);

-- ---------- ASYNC_MAIL_BCC -----------------------------------------------------
ALTER TABLE ASYNC_MAIL_BCC ADD (ID NUMBER(19), TENANT_ID NUMBER(19));
UPDATE ASYNC_MAIL_BCC SET ID = ASYNC_MAIL_BCC_ID_SEQ.NEXTVAL;
UPDATE ASYNC_MAIL_BCC b
   SET TENANT_ID = (SELECT TENANT_ID FROM ASYNC_MAIL_MESS m WHERE m.ID = b.MESSAGE_ID);

-- Drop the old composite PK on (MESSAGE_ID, BCC_IDX). Replace name as needed.
ALTER TABLE ASYNC_MAIL_BCC MODIFY (ID NOT NULL, TENANT_ID NOT NULL);
ALTER TABLE ASYNC_MAIL_BCC ADD CONSTRAINT PK_ASYNC_MAIL_BCC PRIMARY KEY (ID);

CREATE INDEX IDX_ASYNC_MAIL_BCC_TENANT ON ASYNC_MAIL_BCC(TENANT_ID);
CREATE INDEX IDX_ASYNC_MAIL_BCC_MSG    ON ASYNC_MAIL_BCC(MESSAGE_ID);

-- ---------- ASYNC_MAIL_CC ------------------------------------------------------
ALTER TABLE ASYNC_MAIL_CC ADD (ID NUMBER(19), TENANT_ID NUMBER(19));
UPDATE ASYNC_MAIL_CC SET ID = ASYNC_MAIL_CC_ID_SEQ.NEXTVAL;
UPDATE ASYNC_MAIL_CC c
   SET TENANT_ID = (SELECT TENANT_ID FROM ASYNC_MAIL_MESS m WHERE m.ID = c.MESSAGE_ID);


ALTER TABLE ASYNC_MAIL_CC MODIFY (ID NOT NULL, TENANT_ID NOT NULL);
ALTER TABLE ASYNC_MAIL_CC ADD CONSTRAINT PK_ASYNC_MAIL_CC PRIMARY KEY (ID);

CREATE INDEX IDX_ASYNC_MAIL_CC_TENANT ON ASYNC_MAIL_CC(TENANT_ID);
CREATE INDEX IDX_ASYNC_MAIL_CC_MSG    ON ASYNC_MAIL_CC(MESSAGE_ID);

-- ---------- ASYNC_MAIL_HEADER --------------------------------------------------
ALTER TABLE ASYNC_MAIL_HEADER ADD (ID NUMBER(19), TENANT_ID NUMBER(19));
UPDATE ASYNC_MAIL_HEADER SET ID = ASYNC_MAIL_HEADER_ID_SEQ.NEXTVAL;
UPDATE ASYNC_MAIL_HEADER h
   SET TENANT_ID = (SELECT TENANT_ID FROM ASYNC_MAIL_MESS m WHERE m.ID = h.MESSAGE_ID);


ALTER TABLE ASYNC_MAIL_HEADER MODIFY (ID NOT NULL, TENANT_ID NOT NULL);
ALTER TABLE ASYNC_MAIL_HEADER ADD CONSTRAINT PK_ASYNC_MAIL_HEADER PRIMARY KEY (ID);

CREATE INDEX IDX_ASYNC_MAIL_HEADER_TENANT ON ASYNC_MAIL_HEADER(TENANT_ID);
CREATE INDEX IDX_ASYNC_MAIL_HEADER_MSG    ON ASYNC_MAIL_HEADER(MESSAGE_ID);

-- ---------- ASYNC_MAIL_ATTACHMENT (already has ID; only add TENANT_ID) ---------
ALTER TABLE ASYNC_MAIL_ATTACHMENT ADD TENANT_ID NUMBER(19);
UPDATE ASYNC_MAIL_ATTACHMENT a
   SET TENANT_ID = (SELECT TENANT_ID FROM ASYNC_MAIL_MESS m WHERE m.ID = a.MESSAGE_ID);
ALTER TABLE ASYNC_MAIL_ATTACHMENT MODIFY (TENANT_ID NOT NULL);

CREATE INDEX IDX_ASYNC_MAIL_ATTACHMENT_TENANT ON ASYNC_MAIL_ATTACHMENT(TENANT_ID);
